apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: metallb
  sources:
    - repoURL: https://github.com/metallb/metallb.git
      targetRevision: v0.14.5
      path: config/manifests
    - repoURL: 'git@github.com:davidcardoso-homelab/metallb.git'
      targetRevision: main
      path: metalLB/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
